import Foundation
@testable import Haven

// The contract between the Swift ports in Haven/Shared and the TypeScript they
// were ported from: parseProfileUrl / normalizeUrl / nameGuessFromSlug in
// src/lib.ts, and normalizeName in convex/nameSearch.ts.
//
// This matters more than a normal test. The parser decides *identity*:
// (platform, handle) is the dedup key saveSharedProfile writes on. A Swift and
// a TypeScript that disagree about what a URL points at do not produce a
// visible bug, they produce two rows for one person, and nobody finds out.
//
// Everything below this line is generated, never hand-edited. Regenerate with:
//   npx vite-node scripts/dump-shared-fixtures.ts
// and paste the output over the block. If a change to the TypeScript makes
// these fail, either the change is wrong or this file is one regenerate behind.

let normalizeUrlCases: [(input: String, want: String?)] = [
    ("https://instagram.com/mai.makes", "https://instagram.com/mai.makes"),
    ("https://www.linkedin.com/in/mai-tran-8a91b2", "https://www.linkedin.com/in/mai-tran-8a91b2"),
    ("https://x.com/mai_makes", "https://x.com/mai_makes"),
    ("https://twitter.com/mai_makes", "https://twitter.com/mai_makes"),
    ("x.com/mai_makes?s=11", "https://x.com/mai_makes?s=11"),
    ("https://www.linkedin.com/in/mai-tran-8a91b2?utm_source=share_via&utm_content=profile&utm_medium=member_ios", "https://www.linkedin.com/in/mai-tran-8a91b2?utm_source=share_via&utm_content=profile&utm_medium=member_ios"),
    ("https://www.instagram.com/mai.makes/?igsh=MXc4b2k5", "https://www.instagram.com/mai.makes/?igsh=MXc4b2k5"),
    ("https://www.instagram.com/mai.makes/", "https://www.instagram.com/mai.makes/"),
    ("https://m.instagram.com/mai.makes", "https://m.instagram.com/mai.makes"),
    ("https://mobile.twitter.com/mai_makes", "https://mobile.twitter.com/mai_makes"),
    ("HTTPS://WWW.Instagram.COM/MaiMakes", "HTTPS://WWW.Instagram.COM/MaiMakes"),
    ("http://x.com/mai_makes", "http://x.com/mai_makes"),
    ("  instagram.com/mai.makes  ", "https://instagram.com/mai.makes"),
    ("https://vn.linkedin.com/in/mai-tran-8a91b2", "https://vn.linkedin.com/in/mai-tran-8a91b2"),
    ("https://uk.linkedin.com/in/mai-tran-8a91b2", "https://uk.linkedin.com/in/mai-tran-8a91b2"),
    ("https://de.linkedin.com/in/mai-tran-8a91b2", "https://de.linkedin.com/in/mai-tran-8a91b2"),
    ("https://www.linkedin.com/mwlite/in/mai-tran-8a91b2", "https://www.linkedin.com/mwlite/in/mai-tran-8a91b2"),
    ("https://instagram.com/mai.makes/?igsh=abc123&utm=share", "https://instagram.com/mai.makes/?igsh=abc123&utm=share"),
    ("https://www.linkedin.com/in/mai-tran-8a91b2/#profile", "https://www.linkedin.com/in/mai-tran-8a91b2/#profile"),
    ("https://x.com/@MaiMakes", "https://x.com/@MaiMakes"),
    ("https://x.com/@", "https://x.com/@"),
    ("https://x.com/mai_makes/status/17999", "https://x.com/mai_makes/status/17999"),
    ("https://x.com/mai_makes/%73tatus/17999", "https://x.com/mai_makes/%73tatus/17999"),
    ("https://instagram.com/mai.makes/p/Cxyz123", "https://instagram.com/mai.makes/p/Cxyz123"),
    ("https://instagram.com/mai.makes/reel/Cxyz123/", "https://instagram.com/mai.makes/reel/Cxyz123/"),
    ("https://instagram.com/p/Cxyz123", "https://instagram.com/p/Cxyz123"),
    ("https://instagram.com/reel/Cxyz123", "https://instagram.com/reel/Cxyz123"),
    ("https://instagram.com/reels/Cxyz123", "https://instagram.com/reels/Cxyz123"),
    ("https://instagram.com/stories/mai.makes/123", "https://instagram.com/stories/mai.makes/123"),
    ("https://instagram.com/tv/Cxyz123", "https://instagram.com/tv/Cxyz123"),
    ("https://instagram.com/explore/tags/hanoi", "https://instagram.com/explore/tags/hanoi"),
    ("https://instagram.com/accounts/login", "https://instagram.com/accounts/login"),
    ("https://instagram.com/direct/inbox", "https://instagram.com/direct/inbox"),
    ("https://instagram.com/about", "https://instagram.com/about"),
    ("https://x.com/i/flow/login", "https://x.com/i/flow/login"),
    ("https://x.com/home", "https://x.com/home"),
    ("https://x.com/explore", "https://x.com/explore"),
    ("https://x.com/search?q=hanoi", "https://x.com/search?q=hanoi"),
    ("https://x.com/intent/follow", "https://x.com/intent/follow"),
    ("https://x.com/hashtag/hanoi", "https://x.com/hashtag/hanoi"),
    ("https://x.com/messages", "https://x.com/messages"),
    ("https://x.com/notifications", "https://x.com/notifications"),
    ("https://x.com/settings/account", "https://x.com/settings/account"),
    ("https://x.com/compose/tweet", "https://x.com/compose/tweet"),
    ("https://x.com/share", "https://x.com/share"),
    ("https://instagram.com/REEL/Cxyz123", "https://instagram.com/REEL/Cxyz123"),
    ("https://x.com/I/flow/login", "https://x.com/I/flow/login"),
    ("https://x.com/ihateflying", "https://x.com/ihateflying"),
    ("https://instagram.com/pho.reels", "https://instagram.com/pho.reels"),
    ("https://instagram.com/%70/Cxyz123", "https://instagram.com/%70/Cxyz123"),
    ("https://x.com/%69/flow/login", "https://x.com/%69/flow/login"),
    ("https://instagram.com/mai%2Fmakes", "https://instagram.com/mai%2Fmakes"),
    ("https://www.linkedin.com/in/mai-tran-8a91b2/details/experience/", "https://www.linkedin.com/in/mai-tran-8a91b2/details/experience/"),
    ("https://instagram.com/mai.makes/tagged/", "https://instagram.com/mai.makes/tagged/"),
    ("https://www.linkedin.com/company/convex", "https://www.linkedin.com/company/convex"),
    ("https://www.linkedin.com/posts/mai-tran-abc", "https://www.linkedin.com/posts/mai-tran-abc"),
    ("https://www.linkedin.com/pub/mai-tran", "https://www.linkedin.com/pub/mai-tran"),
    ("https://www.linkedin.com/feed/", "https://www.linkedin.com/feed/"),
    ("https://www.linkedin.com/jobs/view/123", "https://www.linkedin.com/jobs/view/123"),
    ("https://www.linkedin.com/in/", "https://www.linkedin.com/in/"),
    ("https://www.linkedin.com/in/nguy%E1%BB%85n-mai", "https://www.linkedin.com/in/nguy%E1%BB%85n-mai"),
    ("https://www.linkedin.com/in/%E0%A4%A", "https://www.linkedin.com/in/%E0%A4%A"),
    ("https://instagram.com/%E0%A4%A", "https://instagram.com/%E0%A4%A"),
    ("https://instagram.com/./mai.makes", "https://instagram.com/./mai.makes"),
    ("https://instagram.com/a/../mai.makes", "https://instagram.com/a/../mai.makes"),
    ("https://x.com/mai_makes/./status/17999", "https://x.com/mai_makes/./status/17999"),
    ("https://instagram.com/%2e/mai.makes", "https://instagram.com/%2e/mai.makes"),
    ("https://instagram.com/a/%2E%2E/mai.makes", "https://instagram.com/a/%2E%2E/mai.makes"),
    ("https://INSTAGRAM.COM/mai.makes", "https://INSTAGRAM.COM/mai.makes"),
    ("https://Instagram.com/mai.makes", "https://Instagram.com/mai.makes"),
    ("https://WWW.instagram.COM/mai.makes", "https://WWW.instagram.COM/mai.makes"),
    ("https://notinstagram.com/mai", "https://notinstagram.com/mai"),
    ("https://evil.example/instagram.com/mai", "https://evil.example/instagram.com/mai"),
    ("instagram.com/mai.makes", "https://instagram.com/mai.makes"),
    ("https://x.com/@@MaiMakes", "https://x.com/@@MaiMakes"),
    ("https://x.com/@@@", "https://x.com/@@@"),
    ("https://facebook.com/mai", "https://facebook.com/mai"),
    ("https://instagram.com.evil.example/mai", "https://instagram.com.evil.example/mai"),
    ("https://instagram.com/", "https://instagram.com/"),
    ("https://x.com", "https://x.com"),
    ("met at the conference", nil),
    ("", nil),
    ("   ", nil),
    ("ftp://instagram.com/mai.makes", nil),
    ("https://example.com/a", "https://example.com/a"),
    ("http://example.com", "http://example.com"),
    ("linkedin.com/in/tony", "https://linkedin.com/in/tony"),
    ("  https://a.com  ", "https://a.com"),
    ("https://x.com/mai.makes", "https://x.com/mai.makes"),
    ("https://x.com/ada_l", "https://x.com/ada_l"),
    ("https://x.com/caf%C3%A9", "https://x.com/caf%C3%A9"),
    ("https://instagram.com/ada_l", "https://instagram.com/ada_l"),
    ("https://instagram.com/caf%C3%A9", "https://instagram.com/caf%C3%A9"),
]

let parseProfileUrlCases: [(input: String, want: ProfileLink?)] = [
    ("https://instagram.com/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://www.linkedin.com/in/mai-tran-8a91b2", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://x.com/mai_makes", ProfileLink(platform: .x, handle: "mai_makes")),
    ("https://twitter.com/mai_makes", ProfileLink(platform: .x, handle: "mai_makes")),
    ("x.com/mai_makes?s=11", ProfileLink(platform: .x, handle: "mai_makes")),
    ("https://www.linkedin.com/in/mai-tran-8a91b2?utm_source=share_via&utm_content=profile&utm_medium=member_ios", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://www.instagram.com/mai.makes/?igsh=MXc4b2k5", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://www.instagram.com/mai.makes/", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://m.instagram.com/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://mobile.twitter.com/mai_makes", ProfileLink(platform: .x, handle: "mai_makes")),
    ("HTTPS://WWW.Instagram.COM/MaiMakes", ProfileLink(platform: .instagram, handle: "MaiMakes")),
    ("http://x.com/mai_makes", ProfileLink(platform: .x, handle: "mai_makes")),
    ("  instagram.com/mai.makes  ", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://vn.linkedin.com/in/mai-tran-8a91b2", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://uk.linkedin.com/in/mai-tran-8a91b2", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://de.linkedin.com/in/mai-tran-8a91b2", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://www.linkedin.com/mwlite/in/mai-tran-8a91b2", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://instagram.com/mai.makes/?igsh=abc123&utm=share", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://www.linkedin.com/in/mai-tran-8a91b2/#profile", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://x.com/@MaiMakes", ProfileLink(platform: .x, handle: "MaiMakes")),
    ("https://x.com/@", nil),
    ("https://x.com/mai_makes/status/17999", nil),
    ("https://x.com/mai_makes/%73tatus/17999", nil),
    ("https://instagram.com/mai.makes/p/Cxyz123", nil),
    ("https://instagram.com/mai.makes/reel/Cxyz123/", nil),
    ("https://instagram.com/p/Cxyz123", nil),
    ("https://instagram.com/reel/Cxyz123", nil),
    ("https://instagram.com/reels/Cxyz123", nil),
    ("https://instagram.com/stories/mai.makes/123", nil),
    ("https://instagram.com/tv/Cxyz123", nil),
    ("https://instagram.com/explore/tags/hanoi", nil),
    ("https://instagram.com/accounts/login", nil),
    ("https://instagram.com/direct/inbox", nil),
    ("https://instagram.com/about", nil),
    ("https://x.com/i/flow/login", nil),
    ("https://x.com/home", nil),
    ("https://x.com/explore", nil),
    ("https://x.com/search?q=hanoi", nil),
    ("https://x.com/intent/follow", nil),
    ("https://x.com/hashtag/hanoi", nil),
    ("https://x.com/messages", nil),
    ("https://x.com/notifications", nil),
    ("https://x.com/settings/account", nil),
    ("https://x.com/compose/tweet", nil),
    ("https://x.com/share", nil),
    ("https://instagram.com/REEL/Cxyz123", nil),
    ("https://x.com/I/flow/login", nil),
    ("https://x.com/ihateflying", ProfileLink(platform: .x, handle: "ihateflying")),
    ("https://instagram.com/pho.reels", ProfileLink(platform: .instagram, handle: "pho.reels")),
    ("https://instagram.com/%70/Cxyz123", nil),
    ("https://x.com/%69/flow/login", nil),
    ("https://instagram.com/mai%2Fmakes", nil),
    ("https://www.linkedin.com/in/mai-tran-8a91b2/details/experience/", ProfileLink(platform: .linkedin, handle: "mai-tran-8a91b2")),
    ("https://instagram.com/mai.makes/tagged/", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://www.linkedin.com/company/convex", nil),
    ("https://www.linkedin.com/posts/mai-tran-abc", nil),
    ("https://www.linkedin.com/pub/mai-tran", nil),
    ("https://www.linkedin.com/feed/", nil),
    ("https://www.linkedin.com/jobs/view/123", nil),
    ("https://www.linkedin.com/in/", nil),
    ("https://www.linkedin.com/in/nguy%E1%BB%85n-mai", ProfileLink(platform: .linkedin, handle: "nguy\u{1ec5}n-mai")),
    ("https://www.linkedin.com/in/%E0%A4%A", nil),
    ("https://instagram.com/%E0%A4%A", nil),
    ("https://instagram.com/./mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://instagram.com/a/../mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://x.com/mai_makes/./status/17999", nil),
    ("https://instagram.com/%2e/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://instagram.com/a/%2E%2E/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://INSTAGRAM.COM/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://Instagram.com/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://WWW.instagram.COM/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://notinstagram.com/mai", nil),
    ("https://evil.example/instagram.com/mai", nil),
    ("instagram.com/mai.makes", ProfileLink(platform: .instagram, handle: "mai.makes")),
    ("https://x.com/@@MaiMakes", ProfileLink(platform: .x, handle: "MaiMakes")),
    ("https://x.com/@@@", nil),
    ("https://facebook.com/mai", nil),
    ("https://instagram.com.evil.example/mai", nil),
    ("https://instagram.com/", nil),
    ("https://x.com", nil),
    ("met at the conference", nil),
    ("", nil),
    ("   ", nil),
    ("ftp://instagram.com/mai.makes", nil),
    ("https://example.com/a", nil),
    ("http://example.com", nil),
    ("linkedin.com/in/tony", ProfileLink(platform: .linkedin, handle: "tony")),
    ("  https://a.com  ", nil),
    ("https://x.com/mai.makes", ProfileLink(platform: .x, handle: "mai.makes")),
    ("https://x.com/ada_l", ProfileLink(platform: .x, handle: "ada_l")),
    ("https://x.com/caf%C3%A9", ProfileLink(platform: .x, handle: "caf\u{e9}")),
    ("https://instagram.com/ada_l", ProfileLink(platform: .instagram, handle: "ada_l")),
    ("https://instagram.com/caf%C3%A9", ProfileLink(platform: .instagram, handle: "caf\u{e9}")),
]

let nameGuessCases: [(slug: String, want: String)] = [
    ("mai-tran-8a91b2", "Mai Tran"),
    ("john-doe", "John Doe"),
    ("m3-tran-8a91b2", "M3 Tran"),
    ("nguy\u{1ec5}n-mai-8a91b2", "Nguy\u{1ec5}n Mai"),
    ("\u{111}\u{1ee9}c-anh", "\u{110}\u{1ee9}c Anh"),
    ("8a91b2", ""),
    ("8a91b2-7c4d", ""),
    ("", ""),
    ("   ", ""),
    ("---", ""),
    ("mai--tran-", "Mai Tran"),
    ("first-last-name216", "First Last"),
    ("mai.makes", "Mai.makes"),
    ("MaiMakes", "MaiMakes"),
    ("mai-tran-\u{661}\u{662}", "Mai Tran \u{661}\u{662}"),
]

let foldNameCases: [(input: String, want: String)] = [
    ("Mai Tran", "mai tran"),
    ("MAI  TRAN", "mai tran"),
    ("  Nguy\u{1ec5}n Mai  ", "nguyen mai"),
    ("\u{110}\u{e0} N\u{1eb5}ng", "da nang"),
    ("\u{111}\u{1ee9}c anh", "duc anh"),
    ("Caf\u{e9}", "cafe"),
    ("", ""),
    ("   ", ""),
    ("Dun\u{9}Dun", "dun dun"),
    ("Jos\u{e9} Garc\u{ed}a", "jose garcia"),
    ("\u{130}stanbul", "istanbul"),
    ("Mai\u{a0}Tran", "mai tran"),
    ("Mai\u{2028}Tran", "mai tran"),
    ("Mai\u{3000}Tran", "mai tran"),
    ("Mai\u{feff}Tran", "mai tran"),
    ("Mai\u{85}Tran", "mai\u{85}tran"),
]

let handleKeyCases: [(input: String, display: String, key: String)] = [
    ("mai.makes", "mai.makes", "mai.makes"),
    ("@mai.makes", "mai.makes", "mai.makes"),
    ("@@mai.makes", "mai.makes", "mai.makes"),
    ("  @Mai.Makes  ", "Mai.Makes", "mai.makes"),
    ("MAI_MAKES", "MAI_MAKES", "mai_makes"),
    ("mai-tran-8a91b2", "mai-tran-8a91b2", "mai-tran-8a91b2"),
    ("@", "", ""),
    ("", "", ""),
    ("   ", "", ""),
    ("caf\u{e9}", "caf\u{e9}", "caf\u{e9}"),
    ("CAF\u{c9}", "CAF\u{c9}", "caf\u{e9}"),
]
